using Microsoft.AspNetCore.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PracaInżynierskaTomaszBaczek.Models;

namespace PracaInżynierskaTomaszBaczek.Pages
{
    public class UserInputLists : ComponentBase
    {
        public List<Texture> Textures { get; set; }
        public List<Tracktype> Tracktypes { get; set; }
        public List<CountryCode> CountryCodes { get; set; }

        public void LoadLists()
        {
            Textures = new List<Texture>()
            {
            new Texture() { Name = @"Textures\carpet.png", Displayname = "Carpet" },
            new Texture() { Name = @"Textures\concrete-lillehammer.png", Displayname = "Concrete Lillehammer" },
            new Texture() { Name = @"Textures\concrete1.png", Displayname = "Concrete 1"},
            new Texture() { Name = @"Textures\concrete2.png", Displayname = "Concrete 2"},
            new Texture() { Name = @"Textures\concrete3.png", Displayname = "Concrete 3"},
            new Texture() { Name = @"Textures\concrete4.png", Displayname = "concrete 4"},
            new Texture() { Name = @"Textures\concrete5.png", Displayname = "Concrete 5"},
            new Texture() { Name = @"Textures\concrete6.png", Displayname = "Concrete 6"},
            new Texture() { Name = @"Textures\corrugatedb.png", Displayname = "Corrugatedb"},
            new Texture() { Name = @"Textures\grating1.png", Displayname = "Grating 1"},
            new Texture() { Name = @"Textures\grating2.png", Displayname = "Grating 2"},
            new Texture() { Name = @"Textures\grating3.png", Displayname = "Grating 3"},
            new Texture() { Name = @"Textures\grid.png", Displayname = "Grid 1"},
            new Texture() { Name = @"Textures\grid2.png", Displayname = "Grid 2"},
            new Texture() { Name = @"Textures\horizontal-wires.png", Displayname = "Horizontal wires"},
            new Texture() { Name = @"Textures\horizontal-wires2.png", Displayname = "Horizontal wires 2"},
            new Texture() { Name = @"Textures\metal.png", Displayname = "Metal"},
            new Texture() { Name = @"Textures\net.png", Displayname = "Net"},
            new Texture() { Name = @"Textures\plate1.png", Displayname = "Plate"},
            new Texture() { Name = @"Textures\plate2.png", Displayname = "Plate 2"},
            new Texture() { Name = @"Textures\railing-glass-cut.png", Displayname = "Railing glass cut"},
            new Texture() { Name = @"Textures\railing-glass.png", Displayname = "Railing glass"},
            new Texture() { Name = @"Textures\rock.png", Displayname = "Rock"},
            new Texture() { Name = @"Textures\rubbermat.png", Displayname = "Rubber mat"},
            new Texture() { Name = @"Textures\rust1.png", Displayname = "Rust"},
            new Texture() { Name = @"Textures\snow.png", Displayname = "Snow"},
            new Texture() { Name = @"Textures\stone1.jpg", Displayname = "Stone"},
            new Texture() { Name = @"Textures\tiles1.png", Displayname = "Tiles"},
            new Texture() { Name = @"Textures\tiles2.png", Displayname = "Tiles 2"},
            new Texture() { Name = @"Textures\tiles3.png", Displayname = "Tiles 3"},
            new Texture() { Name = @"Textures\vertical-wires.png", Displayname = "Vertical wires"},
            new Texture() { Name = @"Textures\window.png", Displayname = "Window"},
            new Texture() { Name = @"Textures\wood1.png", Displayname = "Wood 1"},
            new Texture() { Name = @"Textures\wood1b.png", Displayname = "Wood 1b"},
            new Texture() { Name = @"Textures\wood2.png", Displayname = "Wood 2"},
            new Texture() { Name = @"Textures\wood2b.png", Displayname = "Wood 2b"},
            new Texture() { Name = @"Textures\wood3.png", Displayname = "Wood 3"},
            new Texture() { Name = @"Textures\wood3b.png", Displayname = "Wood 3b"},
            new Texture() { Name = @"Textures\wood4.png", Displayname = "Wood 4"},
            new Texture() { Name = @"Textures\wood4b.png", Displayname = "Wood 4b"},
            new Texture() { Name = @"Textures\wood5.png", Displayname = "Wood 5"},
            new Texture() { Name = @"Textures\wood5b.png", Displayname = "Wood 5b"},
            new Texture() { Name = @"Textures\wood6.png", Displayname = "Wood 6"},
            new Texture() { Name = @"Textures\wood7.png", Displayname = "Wood 7"}
            };

            Tracktypes = new List<Tracktype>()
            {
                new Tracktype(){Type="ceramic"},
                new Tracktype(){Type="default"}
            };

            CountryCodes = new List<CountryCode>()
            {
                new CountryCode(){Country="Afghanistan", Code="AFG"},
                new CountryCode(){Code="ALB", Country="Albania" },
                new CountryCode(){Code="ALG", Country="Algeria" },
                new CountryCode(){Code="AND", Country="Andorra" },
                new CountryCode(){Code="ANG", Country="Angola" },
                new CountryCode(){Code="ANT", Country="Antigua and Barbuda" },
                new CountryCode(){Code="ARG", Country="Argentina" },
                new CountryCode(){Code="ARM", Country="Armenia" },
                new CountryCode(){Code="AUS", Country="Australia" },
                new CountryCode(){Code="AUT", Country="Austria" },
                new CountryCode(){Code="AZE", Country="Azerbaijan" },
                new CountryCode(){Code="BAH", Country="Bahamas" },
                new CountryCode(){Code="BAN", Country="Bangladesh" },
                new CountryCode(){Code="BAR", Country="Barbados" },
                new CountryCode(){Code="BDI", Country="Burundi" },
                new CountryCode(){Code="BEL", Country="Belgium" },
                new CountryCode(){Code="BEN", Country="Benin" },
                new CountryCode(){Code="BHU", Country="Bhutan" },
                new CountryCode(){Code="BIH", Country="Bosnia and Herzegovina" },
                new CountryCode(){Code="BIZ", Country="Belize" },
                new CountryCode(){Code="BKF", Country="Burkina Faso" },
                new CountryCode(){Code="BLR", Country="Belarus" },
                new CountryCode(){Code="BOL", Country="Bolivia" },
                new CountryCode(){Code="BOT", Country="Botswana" },
                new CountryCode(){Code="BRA", Country="Brazil" },
                new CountryCode(){Code="BRN", Country="Bahrain" },
                new CountryCode(){Code="BRU", Country="Brunei Darussalam" },
                new CountryCode(){Code="BUL", Country="Bulgaria" },
                new CountryCode(){Code="CAF", Country="Central African Republic" },
                new CountryCode(){Code="CAM", Country="Cambodia" },
                new CountryCode(){Code="CAN", Country="Canada" },
                new CountryCode(){Code="CGO", Country="Congo, The Repuplic of" },
                new CountryCode(){Code="CHA", Country="Chad" },
                new CountryCode(){Code="CHI", Country="Chile" },
                new CountryCode(){Code="CHN", Country="China" },
                new CountryCode(){Code="CIV", Country="Ivory Coast" },
                new CountryCode(){Code="CMR", Country="Cameroon" },
                new CountryCode(){Code="COD", Country="Congo, The Democratic Republic of" },
                new CountryCode(){Code="COL", Country="Colombia" },
                new CountryCode(){Code="COM", Country="Comoros" },
                new CountryCode(){Code="CPV", Country="Cape Verde" },
                new CountryCode(){Code="CRC", Country="Costa Rica" },
                new CountryCode(){Code="CRO", Country="Croatia" },
                new CountryCode(){Code="CUB", Country="Cuba" },
                new CountryCode(){Code="CYP", Country="Cyprus" },
                new CountryCode(){Code="CZE", Country="Czech Republic" },
                new CountryCode(){Code="DEN", Country="Denmark" },
                new CountryCode(){Code="DJI", Country="Djibouti" },
                new CountryCode(){Code="DMA", Country="Dominica" },
                new CountryCode(){Code="DOM", Country="Dominican Republic" },
                new CountryCode(){Code="ECU", Country="Ecuador" },
                new CountryCode(){Code="EGY", Country="Egypt" },
                new CountryCode(){Code="ERI", Country="Eritrea" },
                new CountryCode(){Code="ESA", Country="El Salvador" },
                new CountryCode(){Code="ESP", Country="Spain" },
                new CountryCode(){Code="EST", Country="Estonia" },
                new CountryCode(){Code="ETH", Country="Ethiopia" },
                new CountryCode(){Code="FIJ", Country="Fiji" },
                new CountryCode(){Code="FIN", Country="Finland" },
                new CountryCode(){Code="FRA", Country="France" },
                new CountryCode(){Code="FSM", Country="Micronesia" },
                new CountryCode(){Code="GAB", Country="Gabon" },
                new CountryCode(){Code="GAM", Country="Gambia" },
                new CountryCode(){Code="GBR", Country="United Kingdom" },
                new CountryCode(){Code="GBS", Country="Guinea-Bissau" },
                new CountryCode(){Code="GEO", Country="Georgia" },
                new CountryCode(){Code="GEQ", Country="Equatorial Guinea" },
                new CountryCode(){Code="GER", Country="Germany" },
                new CountryCode(){Code="GHA", Country="Ghana" },
                new CountryCode(){Code="GRE", Country="Greece" },
                new CountryCode(){Code="GRN", Country="Grenada" },
                new CountryCode(){Code="GUA", Country="Guatemala" },
                new CountryCode(){Code="GUI", Country="Guinea" },
                new CountryCode(){Code="GUY", Country="Guyana" },
                new CountryCode(){Code="HAI", Country="Haiti" },
                new CountryCode(){Code="HON", Country="Honduras" },
                new CountryCode(){Code="HUN", Country="Hungary" },
                new CountryCode(){Code="INA", Country="Indonesia" },
                new CountryCode(){Code="IND", Country="India" },
                new CountryCode(){Code="IRL", Country="Ireland" },
                new CountryCode(){Code="IRN", Country="Iran" },
                new CountryCode(){Code="IRQ", Country="Iraq" },
                new CountryCode(){Code="ISL", Country="Iceland" },
                new CountryCode(){Code="ISR", Country="Israel" },
                new CountryCode(){Code="ITA", Country="Italy" },
                new CountryCode(){Code="JAM", Country="Jamaica" },
                new CountryCode(){Code="JOR", Country="Jordan" },
                new CountryCode(){Code="JPN", Country="Japan" },
                new CountryCode(){Code="KAZ", Country="Kazakhstan" },
                new CountryCode(){Code="KEN", Country="Kenya" },
                new CountryCode(){Code="KGZ", Country="Kyrgyzstan" },
                new CountryCode(){Code="KIR", Country="Kiribati" },
                new CountryCode(){Code="KOR", Country="South Korea" },
                new CountryCode(){Code="KSA", Country="Saudi Arabia" },
                new CountryCode(){Code="KUW", Country="Kuwait" },
                new CountryCode(){Code="LAO", Country="Laos" },
                new CountryCode(){Code="LAT", Country="Latvia" },
                new CountryCode(){Code="LBA", Country="Libya" },
                new CountryCode(){Code="LBR", Country="Liberia" },
                new CountryCode(){Code="LCA" ,Country="Saint Lucia" },
                new CountryCode(){Code="LES" ,Country="Lesotho" },
                new CountryCode(){Code="LIB", Country="Lebanon" },
                new CountryCode(){Code="LIE", Country="Liechtenstein" },
                new CountryCode(){Code="LTU", Country="Lithuania" },
                new CountryCode(){Code="LUX", Country="Luxembourg" },
                new CountryCode(){Code="MAD", Country="Madagascar" },
                new CountryCode(){Code="MAR", Country="Morocco" },
                new CountryCode(){Code="MAS", Country="Malaysia" },
                new CountryCode(){Code="MAW", Country="Malawi" },
                new CountryCode(){Code="MDA", Country="Moldova" },
                new CountryCode(){Code="MDV", Country="Maldives" },
                new CountryCode(){Code="MEX", Country="Mexico" },
                new CountryCode(){Code="MGL", Country="Mongolia" },
                new CountryCode(){Code="MKD", Country="Macedonia" },
                new CountryCode(){Code="MLI", Country="Mali" },
                new CountryCode(){Code="MLT", Country="Malta" },
                new CountryCode(){Code="MNE", Country="Montenegro" },
                new CountryCode(){Code="MON", Country="Monaco" },
                new CountryCode(){Code="MOZ", Country="Mozambique" },
                new CountryCode(){Code="MRI", Country="Mauritius" },
                new CountryCode(){Code="MSH", Country="Marshall Islands" },
                new CountryCode(){Code="MTN", Country="Mauritania" },
                new CountryCode(){Code="MYA", Country="Myanmar" },
                new CountryCode(){Code="NAM", Country="Namibia" },
                new CountryCode(){Code="NCA", Country="Nicaragua" },
                new CountryCode(){Code="NED", Country="Netherlands" },
                new CountryCode(){Code="NEP", Country="Nepal" },
                new CountryCode(){Code="NGR", Country="Nigeria" },
                new CountryCode(){Code="NIG", Country="Niger" },
                new CountryCode(){Code="NOR", Country="Norway" },
                new CountryCode(){Code="NRU" ,Country="Nauru" },
                new CountryCode(){Code="NZL" ,Country="New Zealand" },
                new CountryCode(){Code="OMA" ,Country="Oman" },
                new CountryCode(){Code="PAK" ,Country="Pakistan" },
                new CountryCode(){Code="PAN" ,Country="Panama" },
                new CountryCode(){Code="PAR", Country="Paraguay" },
                new CountryCode(){Code="PER", Country="Peru" },
                new CountryCode(){Code="PHI", Country="Philippines" },
                new CountryCode(){Code="PLE", Country="Palestine" },
                new CountryCode(){Code="PLW", Country="Palau" },
                new CountryCode(){Code="PNG", Country="Papua New Guinea" },
                new CountryCode(){Code="POL", Country="Poland" },
                new CountryCode(){Code="POR", Country="Portugal" },
                new CountryCode(){Code="PRK", Country="North Korea" },
                new CountryCode(){Code="QAT", Country="Qatar" },
                new CountryCode(){Code="ROU", Country="Romania" },
                new CountryCode(){Code="RSA", Country="South Africa" },
                new CountryCode(){Code="RUS", Country="Russia" },
                new CountryCode(){Code="RWA", Country="Rwanda" },
                new CountryCode(){Code="SAM", Country="Samoa" },
                new CountryCode(){Code="SEN", Country="Senegal" },
                new CountryCode(){Code="SEY", Country="Seychelles" },
                new CountryCode(){Code="SIN", Country="Singapore" },
                new CountryCode(){Code="SKN", Country="Saint Kitts and Nevis" },
                new CountryCode(){Code="SLE", Country="Sierra Leone" },
                new CountryCode(){Code="SLO", Country="Slovenia" },
                new CountryCode(){Code="SMR", Country="San Marino" },
                new CountryCode(){Code="SOL", Country="Solomon Islands" },
                new CountryCode(){Code="SOM", Country="Somalia" },
                new CountryCode(){Code="SRB", Country="Serbia" },
                new CountryCode(){Code="SRI", Country="Sri Lanka" },
                new CountryCode(){Code="SSD", Country="South Sudan" },
                new CountryCode(){Code="STP", Country="São Tomé and Príncipe" },
                new CountryCode(){Code="SUD", Country="Sudan" },
                new CountryCode(){Code="SUI", Country="Switzerland" },
                new CountryCode(){Code="SUR", Country="Suriname" },
                new CountryCode(){Code="SVK", Country="Slovakia" },
                new CountryCode(){Code="SWE", Country="Sweden" },
                new CountryCode(){Code="SWZ", Country="Swaziland" },
                new CountryCode(){Code="SYR", Country="Syria" },
                new CountryCode(){Code="TAN", Country="Tanzania" },
                new CountryCode(){Code="THA" ,Country="Thailand" },
                new CountryCode(){Code="TJK" ,Country="Tajikistan" },
                new CountryCode(){Code="TKM" ,Country="Turkmenistan" },
                new CountryCode(){Code="TLS" ,Country="Timor-Leste" },
                new CountryCode(){Code="TOG" ,Country="Togo" },
                new CountryCode(){Code="TON" ,Country="Tonga" },
                new CountryCode(){Code="TPE" ,Country="Taiwan" },
                new CountryCode(){Code="TRI" ,Country="Trinidad and Tobago" },
                new CountryCode(){Code="TUN", Country="Tunisia" },
                new CountryCode(){Code="TUR", Country="Turkey" },
                new CountryCode(){Code="TUV", Country="Tuvalu" },
                new CountryCode(){Code="UAE", Country="United Arab Emirates" },
                new CountryCode(){Code="UGA", Country="Uganda" },
                new CountryCode(){Code="UKR", Country="Ukraine" },
                new CountryCode(){Code="URU", Country="Uruguay" },
                new CountryCode(){Code="USA", Country="United States" },
                new CountryCode(){Code="UZB", Country="Uzbekistan" },
                new CountryCode(){Code="VAN", Country="Vanuatu" },
                new CountryCode(){Code="VAT", Country="Vatican" },
                new CountryCode(){Code="VEN", Country="Venezuela" },
                new CountryCode(){Code="VIE", Country="Vietnam" },
                new CountryCode(){Code="VIN", Country="St. Vincent and the Grenadines" },
                new CountryCode(){Code="YEM", Country="Yemen" },
                new CountryCode(){Code="ZAM", Country="Zambia" },
                new CountryCode(){Code="ZIM", Country="Zimbabwe" }
            };
        }
    }
}
